# build
FROM golang:1.22.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o lund_example_service ./cmd/lund_example_service

# run
FROM alpine:3.18

COPY --from=builder /app/lund_example_service .

EXPOSE 8080
CMD ["./lund_example_service"]
