# build
FROM golang:1.22.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o lund ./cmd/lund

# run
FROM alpine:3.18

COPY --from=builder /app/lund .

EXPOSE 8080
CMD ["./lund"]
